# Generated by Django 4.1.9 on 2023-06-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_organizationcategory_icon"),
        ("guides", "0023_alter_guidereview_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guideprogram",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="guides.guidecategory",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_cities",
                to="users.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_countries",
                to="users.country",
                verbose_name="Страна",
            ),
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="is_moderated",
            field=models.BooleanField(default=False, verbose_name="is_moderated"),
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="is_top",
            field=models.BooleanField(default=False, verbose_name="is_top"),
        ),
        migrations.AddField(
            model_name="guideprogram",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_regions",
                to="users.region",
                verbose_name="Регион",
            ),
        ),
    ]
