# Generated by Django 4.1.9 on 2023-07-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0026_guidecategory_icon_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programschedule",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
