# Generated by Django 4.1.9 on 2023-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0027_alter_programschedule_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guidecategory",
            name="photo",
            field=models.ImageField(default="/static/images/default.svg", upload_to="categories"),
        ),
    ]
