# Generated by Django 4.1.9 on 2023-08-02 08:36

import ckeditor.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0028_alter_guidecategory_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guide",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Общая информация"),
        ),
        migrations.AlterField(
            model_name="guide",
            name="working_time",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Время работы"),
        ),
        migrations.AlterField(
            model_name="guidereview",
            name="text",
            field=ckeditor.fields.RichTextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, message="Минимальная длина отзыва должна превышать 20 символа"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="programplaces",
            name="description",
            field=ckeditor.fields.RichTextField(verbose_name="Описание местности"),
        ),
        migrations.AlterField(
            model_name="programreview",
            name="text",
            field=ckeditor.fields.RichTextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        20, message="Минимальная длина отзыва должна превышать 20 символа"
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="programschedule",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
