# Generated by Django 4.1.9 on 2023-08-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("guides", "0029_alter_guide_description_alter_guide_working_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programschedule",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
