# Generated by Django 4.1.9 on 2023-06-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_delete_gayrat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="category",
        ),
        migrations.RemoveField(
            model_name="application",
            name="description",
        ),
        migrations.RemoveField(
            model_name="application",
            name="region",
        ),
        migrations.AddField(
            model_name="application",
            name="trip_id",
            field=models.IntegerField(default=1, verbose_name="Указываете ID guide or tour"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="application",
            name="type",
            field=models.CharField(
                choices=[("tours", "Tours"), ("guides", "Guides")], default=1, max_length=10, verbose_name="Тип"
            ),
            preserve_default=False,
        ),
    ]
