# Generated by Django 4.1.9 on 2023-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_organizationcategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationcategory",
            name="icon_active",
            field=models.FileField(default="/static/images/cart.svg", upload_to="category_icons"),
        ),
    ]
