name: Production Django deploy MedTour

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: "/root/MedTour"
    - name: Command using from script
      uses: appleboy/ssh-action@master
      env:
        DJANGO_SETTINGS_MODULE: "config.settings.production"
        DJANGO_READ_DOT_ENV_FILE: "True"
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DJANGO_SETTINGS_MODULE, DJANGO_READ_DOT_ENV_FILE
        script_stop: true
        script: |
          export DJANGO_READ_DOT_ENV_FILE=True
          git --work-tree=/root/MedTour --git-dir=/root/MedTour/.git clean -f .
          /root/MedTour/venv/bin/pip install -r /root/MedTour/requirements/production.txt
          /root/MedTour/venv/bin/python /root/MedTour/manage_prod.py migrate
          systemctl restart gunicorn.service
          sh /home/kairat/devops/deploy_msg.sh "${{ github.event.head_commit.message }}" "production"
