name: Develop Django deploy MedTour

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        source: "."
        target: "/root/testMedtour"
    - name: Command using from script
      uses: appleboy/ssh-action@master
      env:
        DJANGO_SETTINGS_MODULE: "config.settings.production"
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: DJANGO_SETTINGS_MODULE
        script_stop: true
        script: |
          export DJANGO_READ_DOT_ENV_FILE=True
          git --work-tree=/root/testMedtour --git-dir=/root/testMedtour/.git clean -f .
          /root/testMedtour/venv/bin/pip install -r /root/testMedtour/requirements/production.txt
          /root/testMedtour/venv/bin/python /root/testMedtour/manage_prod.py migrate
          systemctl restart devmedtour.service
          sh /home/kairat/devops/deploy_msg.sh "${{ github.event.head_commit.message }}" "dev changes"
